security:
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    encoders:
        App\Entity\User:
            algorithm: auto

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true
            #security: false 
            guard:
                authenticators:
                    - App\Guard\TokenAuthenticator
            stateless: true
    access_control:
        - { path: ^/(token|api/doc|regions/import|directors/import), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
