export default {
  name: "Nome",
  lastname: "Cognome",
  save: "Salva",
  cancel: "Annulla",
  home: "Home",
  email: "Email",
  role: "Ruolo",
  management: "Gestione",
  create: "Crea",
  edit: "Modifica",
  admin: "Amministratore",
  chapter: "Capitolo",
  chapters: "Capitoli",
  director: "Director",
  directors: "Directors",
  assistant_director: "Assistant director",
  area_director: "Area director",
  executive_director: "Executive director",
  national: "National",
  pay_type: "Tipo di paga",
  fixed_percentage: "% fissa",
  launch_percentage: "% di lancio",
  select_role: "Selezina ruolo",
  account: "Account",
  free_account: "Account free",
  monthly: "Mensile",
  annual: "Annuale",
  randa: "Randa",
  region: "Region",
  change_region: "Cambia region",
  successfuly_created: " creato correttamente",
  successfuly_edited: " modificato correttamente",
  user_with_role_exists: "L'utente con questo ruolo è già esistente.",
  invalid_email: "Indirizzo email non valido"
};
