export default {
  name: "Nome",
  lastname: "Cognome",
  save: "Salva",
  cancel: "Annulla",
  home: "Home",
  email: "Email",
  role: "Ruolo",
  management: "Gestione",
  authentication_error: "Errore di autenticazione",
  create: "Crea",
  edit: "Modifica",
  admin: "Amministratore",
  chapter: "Capitolo",
  chapters: "Capitoli",
  director: "Director",
  director_created: "Director creato correttamente",
  director_edited: "Director modificato correttamente",
  directors: "Directors",
  assistant_director: "Assistant director",
  area_director: "Area director",
  executive_director: "Executive director",
  national: "National",
  pay_type: "Tipo di paga",
  fixed_percentage: "% fissa",
  launch_percentage: "% di lancio",
  select_role: "Selezina ruolo",
  account: "Account",
  free_account: "Account free",
  monthly: "Mensile",
  annual: "Annuale",
  randa: "Randa",
  region: "Region",
  change_region: "Cambia region",
  successfuly_created: " creato correttamente",
  successfuly_edited: " modificato correttamente",
  user_with_role_exists: "L'utente con questo ruolo è già esistente.",
  invalid_email: "Indirizzo email non valido",
  chapter_suspended: "Capitolo sospeso correttamente",
  chapter_resume: "Capitolo ripreso correttamente",
  chapter_suspended_error: "Errore nella sospensione del capitolo",
  chapter_resume_error: "Errore nella ripresa del capitolo",
  core_group_launch_error: "Errore nel lancio del core group",
  core_group_launched: "Core group lanciato!",
  chapter_launch_error: "Errore nel lancio del capitolo",
  chapter_launched: "Capitolo lanciato!",
  confirm: "Conferma",
  send_proposal: "Manda proposta"
};
