#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# oauth2_server:
#     resource: "@OAuth2ServerBundle/Controller/"
#     type:     annotation
#     prefix:   /

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }